version: 2.1

orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
    test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run:
            name: Run tests
            command: 'npm run test'

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
          - test