version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run: npm run test